### ISSUE TITLE
Why Mercury, Have Thy Forsaken Me?

### ISSUE THREAD

**Issue by ZeyStormborn** [timotejroiko/astrobot-docs#2]
I am having issues being able to add planets to my bot settings. I choose to add a planet and it tells me "no valid planet to add" I am not sure if I have selected something that I shouldn't have that has stopped me from being able to add them. Any help you can give me would be much appreciated it.

**Comment by ghost** [comment]
@ZeyStormborn Join tim's support server Astro Dev: https://discord.gg/DjRYnUwh95
You are better able to get help there.

**Comment by timotejroiko** [comment]
i had no idea this issue existed lmao

**Comment by timotejroiko** [comment]
forgotten in time

**Comment by ZeyStormborn** [comment]
Who are you?

**Comment by ZeyStormborn** [comment]
oh okay I remember sending a report about an issue but idr what the issue
was now lol
